language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'CREATE DATABASE IF NOT EXISTS php_SRePS;'
  - mysql php_SRePS < database/php_sreps.sql
  - "mysql -u root -e \"GRANT ALL PRIVILEGES ON *.* TO ''@'localhost';\""
  - npm install karma phantomjs-prebuilt jasmine-core karma-phantomjs-launcher karma-jasmine karma-chrome-launcher --save-dev

script:
  - ./vendor/bin/phpunit
  - node_modules/karma/bin/karma start karma.conf.js --single-run

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

notifications:
  email: false
